AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  microservicehttpendpoint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: >-
        A simple function that sends a synchronous request to rekognition and returns the response.
      MemorySize: 128
      Timeout: 10
      Policies: []
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
